### ISSUE TITLE
Prune inactive committers

### ISSUE THREAD

**Issue by akurtakov** [eclipse-platform/.eclipsefdn#7]
In the last 2 years there hasn't been contributions (according to https://projects.eclipse.org/projects/eclipse.platform stats) from:
* Andrew Obuchowicz
* [x] Thomas Wolf 
* Julian Honnen
* Karsten Thoms
* [x] Eric Williams
* [x] Dirk Fauth
* [x] Szymon Ptaszkiewicz
* Mike Wilson
* Markus Duft

Please state here whether you want to stay committer on the project.
Retiring inactive committers will happen after October 1st 2024 for people that haven't requested to remain such.

**Comment by akurtakov** [comment]
Mail sent to project list to inform people https://www.eclipse.org/lists/platform-dev/msg04041.html

**Comment by fipro78** [comment]
I would also like to keep my committer status

**Comment by ericwill** [comment]
I would like to keep my committer status

**Comment by JavaJoeS** [comment]
I would like to keep my committer status

**Comment by sptaszkiewicz** [comment]
I would like to keep my committer status.

**Comment by akurtakov** [comment]
@JavaJoeS I can't link the github account to committer name. Would you please share that info here?

**Comment by akurtakov** [comment]
> @JavaJoeS I can't link the github account to committer name. Would you please share that info here?

Are you really one of the committers? If yes, please say who exaclty.

**Comment by akurtakov** [comment]
The following committers have been retired:
* Andrew Obuchowicz
* Julian Honnen
* Karsten Thoms 
* Mike Wilson (special thanks for the many many years or driving the project ahead, there is no "emeritus" status anymore to express this)
* Markus Duft
